### PR TITLE
[WIP] fix: get npm audit to pass

### PR DESCRIPTION
**Pull request by garbados**
The command `npm audit` reports several vulnerabilities in the node-jq project. This PR attempts to resolve those vulnerabilities.

Here is the current output of `npm audit`:

```
$ npm audit
=== npm audit security report ===                        
                                                                                
# Run  npm update minimatch --depth 5  to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ isparta [dev]                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ isparta > istanbul > fileset > glob > minimatch              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/118                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ codeclimate-test-reporter [dev]                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ codeclimate-test-reporter > request > hawk > boom > hoek     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ codeclimate-test-reporter [dev]                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ codeclimate-test-reporter > request > hawk > cryptiles >     │
│               │ boom > hoek                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ codeclimate-test-reporter [dev]                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ codeclimate-test-reporter > request > hawk > hoek            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ codeclimate-test-reporter [dev]                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ codeclimate-test-reporter > request > hawk > sntp > hoek     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ isparta [dev]                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ isparta > istanbul > fileset > minimatch                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/118                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Memory Exposure                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tunnel-agent                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.6.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ codeclimate-test-reporter [dev]                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ codeclimate-test-reporter > request > tunnel-agent           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/598                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 7 vulnerabilities (5 moderate, 2 high) in 13384 scanned packages
  run `npm audit fix` to fix 1 of them.
  6 vulnerabilities require manual review. See the full report for details.
```

### CODE REVIEW

**Comment by garbados** [comment]
Only two dependencies are responsible for these issues:

- [isparta](https://www.npmjs.com/package/isparta), an unmaintained tool for producing code coverage reports.
- [codeclimate-test-reporter](https://www.npmjs.com/package/codeclimate-test-reporter), which posts code coverage to a remote service.

These dependencies can be replaced by [nyc](https://www.npmjs.com/package/nyc), which is more actively maintained.

**Comment by davesnx** [comment]
Hey @garbados 

The tests fails because the `install-binary` stopped working properly. Probably with the update of bin-build dependency. We have already a working 2.2.0 version on master working. Would you like to rebase it with master and keep working on your PR. 

Seems pretty interesting to not have any vulnerability issue on this module.

Thanks

**Comment by garbados** [comment]
`bin-build` 2.2.0 includes a vulnerable version of `tunnel-agent`. Upgrading to 3.0.0 fixes this issue, but also causes this error:

```
TypeError: BinBuild is not a constructor
    at Object.<anonymous> (/home/travis/build/sanack/node-jq/scripts/install-binary.js:62:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

The `binBuild.url(...).then(...)` syntax works, but not this `new BinBuild()` one.

**Comment by garbados** [comment]
Great! Reverting to the `binBuild.url` syntax fixed things. Wahoo!

I have also added a `posttest` script which performs the auditing automatically after the test suite has passed.

**Comment by garbados** [comment]
Yarn has its own audit command, [yarn audit](https://yarnpkg.com/lang/en/docs/cli/audit/), which I have tried and failed to involve in the test suite as it is not included in the Travis' cached version of Yarn. I've left it out of the test suite for now because I lack the credentials to update the project's cache.

**Pull request merged**
