### PR TITLE
Typescript code refactor

### PR DESCRIPTION
**Pull request by jpandersen87**
I've created a fork that moves the project into using typescript for coding/testing/linting. In addition, I've refactored the jq code into a JQ class. A jq object can be created with alternative jq path, parameter option defaults, parameter builder map defaults, and child process spawn options. A jq object is created with defaults and exposes its functions at all prior exports to maintain backwards compatibility. Has parameter options builder refactor. Library now supports declaring locations in parameter options. Library still passes all tests. I've ensured that coverage doesn't decrease (in fact, reaching 100%). All non-obsolete files I could find are updated to accept typescript (ex: codeclimate).

This is a big refactor and is presumptuous on a lot of changes, so I don't necessarily expect this to be accepted as-is.

### CODE REVIEW

**Comment by jpandersen87** [comment]
Would also close PRs #199 and #198. Will review the CI/CC failures immediately.

**Comment by jpandersen87** [comment]
Not sure how to reduce the complexity any more than I have 🤔. Everything else seems to be satisfactory.

**Comment by jpandersen87** [comment]
Would also close PRs #201 and #202. I need to fix code coverage back to 100% since the joi changes.

**Comment by davesnx** [comment]
Hey @jpandersen87 

We didn't have a need to add types to `node-jq` since there are not many interfaces that we need to cover (just `.run`). Their parameters are quite simple, we could have a benefit from adding types there, I agree. 

I love the addition of Joi on the validation. I think that many of the new issues that have been opened are related to lack of documentation reading and unexpected result for the user.

A run-time validation it's a very good idea to solve it. I see that it's a very different scope of this PR.

We (@mackermans and I) are not very comfortable with rewriting the entire project into TypeScript. I would suggest to close this PR and we could work on a more incremental work:

- First adding types and keep the js implementation (add a d.ts).
- Improving run-time validation with Joi (or any other implementation).

And further, we can think of finishing to move it to TypeScript entirely.

**Comment by davesnx** [comment]
I'm very sad to discard this PR since there's a lot of time invested in this and we really appreciate the contribution.

**Comment by jpandersen87** [comment]
Absolutely no problem. I knew a typescript rebase for this project would've been in the "too drastic" change category, but took a shot at it anyways. I'll move my fork master to a named branch and rebase master and go your preferred route. Thank you for taking the time to look at this PR. 😃

**Pull request closed without merging**
