### PR TITLE
Adding the --sort-keys flag via {sort:true} option

### PR DESCRIPTION
**Pull request by tlhunter**

### CODE REVIEW

**Comment by tlhunter** [comment]
@mackermans @davesnx failures appear unrelated (Yarn / Node v4 stuff).

**Comment by mackermans** [comment]
@tlhunter I just merged #112, which drops support for node v4. Could you merge master into your branch? Tests should pass now.

**Comment by tlhunter** [comment]
@mackermans looks like they're happy now (-:

**Comment by mackermans** [comment]
Thanks for your contribution @tlhunter 🙂

**Pull request merged**
