### PR TITLE
move build dependencies out of production package

### PR DESCRIPTION
**Pull request by Liath**
I'm using node-jq in AWS Lambda and the ~90Mb for build dependencies is having a noticeable effect on my cold-boot times when they can be pretty easily moved into devDepends.
PRing this just in case I'm not the only one facing this issue and because it changes almost nothing except for `npm i --production` package size.

### CODE REVIEW

**Comment by Liath** [comment]
Not sure what can be done about the CI test failure, the error that is show is apparently a bug in npm according to `postinstall-build`s maintainer. https://www.npmjs.com/package/postinstall-build#bugs-in-npm

**Comment by Liath** [comment]
I added the default circleci config.yml and set it to use node:latest which seems to have cleared up the build issues.

**Comment by mackermans** [comment]
Hi @Liath,

Thanks for your contribution!

I appreciate the effort of reducing the production package size, that seems to be a good step forward. I do have some concerns though:

1. Could you share with me how you measured the size of the `node_modules` folder after running `npm install --production node-jq`? The command I used on Mac was `du -sh node_modules`. I seem to get a lower production package size than 90M, instead it’s 9.2M on later node versions. AWS Lambda supports `node@6.10` and `node@4.3` so I included both in my tests. Here are the results:

`node@8.1.2`, `npm@5.0.3`: 9.2M
`node@6.10.3`, `npm@3.10.10`: 9.2M
`node@4.3.2`, `npm@2.14.12`: 21M

2. `postinstall-build` temporarily installs devDependencies ([source](https://www.npmjs.com/package/postinstall-build#what-does-it-do)), so I am not sure how it could increase cold boot time. Isn't that your goal, as opposed to reducing production package size overall? 

3. Not related to your issue, but if your PR is to be merged, I would appreciate it if you removed the `.circleci/config.yml`. We might consider adding CircleCI in the future again, however, for now, we are happily running Travis-CI :smile:

**Comment by Liath** [comment]
Woops, I measured 90M before pruning for production. The actual starting measurement on Ubuntu for `node@8.0.0` and `npm@5.0.4` is 11M. Not as much of difference now:
<details>
<summary>Before:</summary>
<pre>
$ du -h --max-depth 1 node_modules | sort -h
4.0K	node_modules/.bin
16K	node_modules/array-differ
16K	node_modules/capture-stack-trace
16K	node_modules/first-chunk-stream
16K	node_modules/get-stdin
16K	node_modules/gulp-rename
16K	node_modules/is-bzip2
16K	node_modules/is-gzip
16K	node_modules/is-tar
16K	node_modules/is-zip
16K	node_modules/lowercase-keys
16K	node_modules/set-immediate-shim
16K	node_modules/strip-outer
20K	node_modules/ansi-regex
20K	node_modules/ansi-styles
20K	node_modules/archive-type
20K	node_modules/array-uniq
20K	node_modules/array-unique
20K	node_modules/arr-diff
20K	node_modules/arr-flatten
20K	node_modules/async-each-series
20K	node_modules/beeper
20K	node_modules/brace-expansion
20K	node_modules/buffer-to-vinyl
20K	node_modules/concat-stream
20K	node_modules/create-error-class
20K	node_modules/decompress
20K	node_modules/decompress-response
20K	node_modules/duplexer2
20K	node_modules/duplexer3
20K	node_modules/each-async
20K	node_modules/end-of-stream
20K	node_modules/escape-string-regexp
20K	node_modules/expand-brackets
20K	node_modules/extend-shallow
20K	node_modules/ext-list
20K	node_modules/ext-name
20K	node_modules/fancy-log
20K	node_modules/filename-regex
20K	node_modules/filename-reserved-regex
20K	node_modules/filenamify
20K	node_modules/for-in
20K	node_modules/for-own
20K	node_modules/get-proxy
20K	node_modules/glob-parent
20K	node_modules/glogg
20K	node_modules/gulp-decompress
20K	node_modules/has-ansi
20K	node_modules/has-gulplog
20K	node_modules/inflight
20K	node_modules/ip-regex
20K	node_modules/is-absolute
20K	node_modules/is-dotfile
20K	node_modules/is-equal-shallow
20K	node_modules/is-extendable
20K	node_modules/is-extglob
20K	node_modules/is-natural-number
20K	node_modules/is-number
20K	node_modules/is-obj
20K	node_modules/isobject
20K	node_modules/is-plain-obj
20K	node_modules/is-posix-bracket
20K	node_modules/is-primitive
20K	node_modules/is-redirect
20K	node_modules/is-relative
20K	node_modules/is-retry-allowed
20K	node_modules/is-stream
20K	node_modules/isurl
20K	node_modules/is-utf8
20K	node_modules/is-valid-glob
20K	node_modules/lodash._basecopy
20K	node_modules/lodash._basetostring
20K	node_modules/lodash._basevalues
20K	node_modules/lodash._getnative
20K	node_modules/lodash._isiterateecall
20K	node_modules/lodash._reescape
20K	node_modules/lodash._reevaluate
20K	node_modules/lodash._reinterpolate
20K	node_modules/lodash.restparam
20K	node_modules/lodash._root
20K	node_modules/lodash.templatesettings
20K	node_modules/merge-stream
20K	node_modules/mimic-response
20K	node_modules/node-status-codes
20K	node_modules/object-assign
20K	node_modules/once
20K	node_modules/onetime
20K	node_modules/ordered-read-streams
20K	node_modules/os-tmpdir
20K	node_modules/path-dirname
20K	node_modules/path-is-absolute
20K	node_modules/p-cancelable
20K	node_modules/p-finally
20K	node_modules/pify
20K	node_modules/pinkie-promise
20K	node_modules/prepend-http
20K	node_modules/p-timeout
20K	node_modules/read-all-stream
20K	node_modules/repeat-element
20K	node_modules/sort-keys
20K	node_modules/sort-keys-length
20K	node_modules/sparkles
20K	node_modules/strip-ansi
20K	node_modules/strip-bom
20K	node_modules/strip-bom-stream
20K	node_modules/strip-eof
20K	node_modules/strip-json-comments
20K	node_modules/sum-up
20K	node_modules/supports-color
20K	node_modules/temp-dir
20K	node_modules/timed-out
20K	node_modules/to-absolute-glob
20K	node_modules/trim-repeated
20K	node_modules/unique-stream
20K	node_modules/unzip-response
20K	node_modules/url-parse-lax
20K	node_modules/url-regex
20K	node_modules/url-to-options
20K	node_modules/vali-date
20K	node_modules/wrap-fn
20K	node_modules/wrappy
24K	node_modules/balanced-match
24K	node_modules/buffer-crc32
24K	node_modules/chalk
24K	node_modules/clone-stats
24K	node_modules/co
24K	node_modules/error-ex
24K	node_modules/expand-range
24K	node_modules/get-stream
24K	node_modules/glob-stream
24K	node_modules/gulplog
24K	node_modules/inherits
24K	node_modules/ini
24K	node_modules/is-glob
24K	node_modules/kind-of
24K	node_modules/lodash.escape
24K	node_modules/lodash.isarguments
24K	node_modules/lodash.isarray
24K	node_modules/lodash.keys
24K	node_modules/normalize-path
24K	node_modules/object.omit
24K	node_modules/pend
24K	node_modules/p-event
24K	node_modules/pinkie
24K	node_modules/regex-cache
24K	node_modules/remove-trailing-separator
24K	node_modules/repeat-string
24K	node_modules/strip-dirs
24K	node_modules/time-stamp
24K	node_modules/ware
28K	node_modules/braces
28K	node_modules/graceful-readlink
28K	node_modules/process-nextick-args
28K	node_modules/util-deprecate
32K	node_modules/fill-range
32K	node_modules/fs.realpath
32K	node_modules/is-buffer
32K	node_modules/lodash.template
32K	node_modules/stream-shift
32K	node_modules/tunnel-agent
36K	node_modules/content-disposition
36K	node_modules/dateformat
36K	node_modules/deep-extend
36K	node_modules/file-type
36K	node_modules/ieee754
36K	node_modules/isarray
36K	node_modules/is-arrayish
36K	node_modules/replace-ext
36K	node_modules/stream-combiner2
36K	node_modules/string_decoder
40K	node_modules/concat-map
40K	node_modules/xtend
44K	node_modules/caw
44K	node_modules/core-util-is
44K	node_modules/exec-series
44K	node_modules/extglob
44K	node_modules/is-object
44K	node_modules/is-url
44K	node_modules/is-valid-path
44K	node_modules/make-dir
44K	node_modules/preserve
44K	node_modules/safe-buffer
44K	node_modules/stat-mode
44K	node_modules/vinyl-assign
48K	node_modules/base64-js
48K	node_modules/graceful-fs
48K	node_modules/jsonify
48K	node_modules/minimatch
48K	node_modules/tar-stream
52K	node_modules/clone
52K	node_modules/extend
52K	node_modules/through
56K	node_modules/commander
56K	node_modules/fd-slicer
56K	node_modules/parse-json
56K	node_modules/through2-filter
60K	node_modules/decompress-unzip
60K	node_modules/got
60K	node_modules/rc
64K	node_modules/is-invalid-path
64K	node_modules/parse-glob
68K	node_modules/bl
68K	node_modules/glob
68K	node_modules/lazystream
68K	node_modules/lodash.isequal
68K	node_modules/typedarray
68K	node_modules/vinyl
72K	node_modules/gulp-sourcemaps
72K	node_modules/yauzl
76K	node_modules/json-stable-stringify
76K	node_modules/seek-bzip
84K	node_modules/bin-build
92K	node_modules/convert-source-map
92K	node_modules/duplexify
92K	node_modules/has-symbol-support-x
92K	node_modules/has-to-string-tag-x
100K	node_modules/glob-base
100K	node_modules/minimist
100K	node_modules/uuid
104K	node_modules/randomatic
108K	node_modules/decompress-tar
108K	node_modules/decompress-tarbz2
108K	node_modules/decompress-targz
108K	node_modules/rimraf
108K	node_modules/tempfile
116K	node_modules/micromatch
176K	node_modules/mime-db
176K	node_modules/readable-stream
180K	node_modules/gulp-util
188K	node_modules/mkdirp
188K	node_modules/through2
232K	node_modules/vinyl-fs
236K	node_modules/buffer
280K	node_modules/multipipe
588K	node_modules/download
924K	node_modules/unbzip2-stream
11M	node_modules
</pre>
</details>
<details>
<summary>After:</summary>
<pre>
du -h --max-depth 1 node_modules | sort -h  
4.0K	node_modules/.bin
20K	node_modules/is-extglob
20K	node_modules/is-glob
20K	node_modules/is-invalid-path
20K	node_modules/strip-eof
44K	node_modules/is-valid-path
44K	node_modules/postinstall-build
804K	node_modules/fsevents
1000K	node_modules
</pre>
</details>
<br />
<p>In Lambda, you upload a zip of everything your code will need because they won't perform any build steps for you (unlike heroku which is kind enough to run npm. So, on a cold-boot, Lambda will fetch, unpack, require your entrypoint, and then call an exported event handler function. It will try to keep your code loaded for a while so this doesn't happen often. Unfortunately, the function I'm working on has to load very quickly so the smaller I can make the zip package the shorter the load time.
Part of the creation process for these packages is to run `npm prune --production` to pare out as much cruft as possible. `postinstall-build` will install devDepends to make the build happen if the resulting artifact (`jq` in this case) isn't present, but once it's done those packages are removed. </p>

I'll gladly drop the circleci stuff, I was just trying to clear up the build checks. :)

**Pull request closed without merging**
