### PR TITLE
Add '-r' (output raw string) support for jq

### PR DESCRIPTION
**Pull request by huan**
Support '-r' options for jq by setting  options.raw = true

### CODE REVIEW

**Comment by davesnx** [comment]
Thanks for the PR, @huan 

I would be happy to accept it if there are some unit tests around it

**Comment by huan** [comment]
Great, I'll add some unit tests later.

**Comment by huan** [comment]
@davesnx I had added two unit tests:

`-r` and no-`-r`.

Please review.

**Pull request merged**
