### PR TITLE
Create bin entry

### LINKED ISSUE #142: Add a bin declaration in package.json
Would be nice to also have a link to jq in node_modules/.bin

### PR DESCRIPTION
**Pull request by alxndrsn**
Closes #142

### CODE REVIEW

**Comment by davesnx** [comment]
I'm not sure about this change. We don't publish outside jq because our API isn't a CLI.  Exposing `jq` as a binary doesn't seem right. 

Is there any problem that we are solving here or just 'beauty'?

**Comment by stefaneg** [comment]
My reasoning is that since jq is a CLI, having installed it, it is wasteful not to have it accessible, and having to install another package in the case I do (which I do). There are other packages intended to install the CLI only, with no js wrapper provided. The ones I've tried are buggy though.

Regarding the global install, I do not see why anyone would install a package which provides no binary globally, at least I have never encountered such a use-case.

But in the end, this is a matter of the preferences of the project owners. I agree that it is conceptually more pure not to publish the jq binary, while I would argue that it is more practical to do so.

**Comment by alxndrsn** [comment]
> We don't publish outside jq because our API isn't a CLI. Exposing jq as a binary doesn't seem right.

I guess I've misunderstood.  Is the binary at `bin/jq` the standard `jq`?

We're using `jq` in CLI scripts and npm scripts in projects where node dependencies are included via `package.json`/`node_modules`. We currently require developers to install `jq` as a system dependency, which then allows us to use it in scripts in `package.json` (e.g. `npm run some-script`).

One of my team suggested we instead depend on `node-jq`, and replace calls to `jq` with calls to `node_modules/node-jq/bin/jq`.  This change would allow us to skip the system dependency without having to change references to `jq` in npm scripts to `node_modules/node-jq/bin/jq`.

**Comment by stefaneg** [comment]
@alxndrsn This is exactly what I do currently. It is however a brittle and a hackish approach, since it is depending on how the non-published internals of node-jq happen to be structured in the current version.

**Comment by davesnx** [comment]
Hey @alxndrsn and @stefaneg 

It's relying on the current internal on node-jq, If you are using the 1.3.x version shouldn't be a problem. We don't have any plans to change that, but in the long-run I can't promise that woudn't change.

I'm happy to merge this one, but as soon as we break that compatibility we should remove the bin on the package.json.

**Comment by imoark** [comment]
It appears that it doesn't install `./node_modules/node-jq/bin` folder to my local `./node_modules`.
I tried to install jq manually by apt-get.
I tried to install node-jq globally.

### Error Message

```
sh: 1: ./node_modules/node-jq/bin/jq: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! create-react-app@2.2.1 start: `dotenv=.env.$(./node_modules/node-jq/bin/jq --raw-output '.envName' ./amplify/.config/local-env-info.json) && echo ' $dotenv ='$dotenv'' && env-cmd $dotenv  cross-env APP_TYPE=site umi dev`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the create-react-app@2.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aquanow/.npm/_logs/2019-05-07T00_28_14_452Z-debug.log
```

## Environment

I'm running it on the WSL (Windows Subsytem Linux) terminal on a Windows machine.
```bash
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

nodejs version:
```bash
Node.js v11.15.0
linux 4.4.0-17763-Microsoft
```
npm version:
```bash
6.7.0
```
node-jq version:
```bash
"version": "1.5.0"
```

**Pull request merged**
